name: Node.js CI

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies 
      run: yarn install
      working-directory: ./client

    - name: Run lint
      run: yarn lint
      working-directory: ./client

    - name: Run tests
      run: yarn test
      working-directory: ./client
      
    - name: Install dependencies 
      run: yarn install
      working-directory: ./server

    - name: Run lint
      run: yarn lint
      working-directory: ./server

    - name: Run tests
      run: yarn test
      working-directory: ./server
